# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'SportApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportApp
	  pod 'Alamofire', '~> 5.6'
	  pod 'Kingfisher', '~> 7.0'
    pod 'Reachability', '~> 3.2'
	  pod 'TTGSnackbar', '~> 1.11'
	  pod 'lottie-ios', '~> 4.1'

  target 'SportAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportAppUITests' do
    # Pods for testing
  end

end
